spring:
  application:
    name: authService
  datasource:
    url: jdbc:mysql://localhost:3306/xhzh?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: XinHong12345
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    serviceUrl:
      defaultZone: http://test:test@localhost:8081/eureka/
server:
  port: 8100
security:
  user:
    name: test
    password: test
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
